const COUPONS = [
  { id: 1, title: "The “Come Here” Kiss", body: "Redeem this coupon whenever you want a kiss.\nFine print: I decide when it ends." },
  { id: 2, title: "Unlimited Cuddles", body: "One unlimited cuddle session with your favourite girl.\nCuddling may lead to kissing. Kissing may lead to absolutely anything." },
  { id: 3, title: "The Full-Body Massage", body: "A private massage, performed by your girlfriend.\nCondition: you must lie still and enjoy it. Bonus: I might get distracted." },
  { id: 4, title: "You Pick the Movie", body: "You choose the movie. I provide the snacks, cuddles and company.\nReview: we both know we probably won’t finish the movie." },
  { id: 5, title: "Breakfast in Bed", body: "Wake up to breakfast made especially for you.\nAdditional service: your girlfriend may be included in bed. No complaints accepted." },
  { id: 6, title: "Your Wish Is My Command", body: "For one day, you get to make one reasonable request. I’ll do my best to make it happen.\nChoose wisely, birthday boy." },
  { id: 7, title: "Gaming Night", body: "Unlimited gaming time. No complaining. No interruptions. No “are you almost done?”\nBUT: I reserve the right to demand kisses between rounds." },
  { id: 8, title: "Make-Out Session", body: "One uninterrupted make-out session. Duration: entirely up to us. Location: wherever appropriate.\nWarning: may be difficult to stop." },
  { id: 9, title: "Your Personal Cheerleader", body: "One day of compliments, encouragement and reminding you exactly how attractive I think you are.\nSide effect: potentially unbearable confidence." },
  { id: 10, title: "“You Were Right” Pass", body: "Congratulations. You were right. You may use this coupon once to hear me admit it.\nDo not get used to this." },
  { id: 11, title: "Kiss Attack", body: "At a completely random moment, I get to attack you with kisses. No warning. No escape.\nYou have been warned." },
  { id: 12, title: "Secret Date", body: "Dress nicely. Be ready at the agreed time. Ask no questions. I’ll handle the rest.\nYour only responsibility: be handsome." },
  { id: 13, title: "One Very Flirty Night", body: "Tonight is all about you. Good food. Good music. Good company.\nAnd absolutely no boring bedtime routine." },
  { id: 14, title: "The “I Can’t Keep My Hands Off You” Pass", body: "Redeem this coupon for one evening where I make it very obvious exactly how much I want you.\nDisclaimer: this coupon may be redeemed repeatedly." },
  { id: 15, title: "Lazy Bed Day", body: "No alarms. No responsibilities. Just us, snacks, movies, cuddles and staying in bed for longer than we should.\nGetting out of bed is strongly discouraged." },
  { id: 16, title: "Compliment Overload", body: "For one day, you receive an unreasonable amount of compliments. You are handsome. You are sexy. You are adorable.\nAnd unfortunately for you, I’m very attracted to you." },
  { id: 17, title: "You Choose My Outfit", body: "For one date, you get to choose what I wear. Within reason.\nAnd yes, you can make it a little cheeky." },
  { id: 18, title: "Bad Day = Girlfriend Duty", body: "Feeling stressed? Come here. You get hugs, kisses, cuddles, reassurance and my undivided attention.\nRefills unlimited." },
  { id: 19, title: "One Favour", body: "You may ask me to do one thing you’ve been wanting me to do. Keep it reasonable. Keep it cute.\nOr surprise me." },
  { id: 20, title: "Shower for Two", body: "One shower together. No rushing. No phones. Just us.\nI’ll let you decide what happens next." },
  { id: 21, title: "King for a Night", body: "Tonight, you’re in charge. You choose the music, the food, the movie, the activity.\nJust remember who’s giving you this coupon." },
  { id: 22, title: "Morning Kiss Delivery", body: "One morning where you receive kisses before you’re even fully awake. Delivery: right to your pillow.\nTip: staying in bed may avoid additional deliveries." },
  { id: 23, title: "Memory Lane", body: "One night of looking through our photos, videos and favourite memories. We’ll laugh. We’ll reminisce.\nWe’ll probably get distracted again." },
  { id: 24, title: "One Night With Your Girl", body: "No phones. No distractions. Just you and me. I’ll make sure you feel exactly how loved, wanted and appreciated you are.\nCome prepared for attention." },
  { id: 25, title: "The Birthday Boy Special", body: "You’ve officially reached 25! This one comes with extra kisses, extra cuddles, extra affection, extra flirting, extra attention, extra love.\nYou are my favourite person to annoy, kiss, cuddle, laugh with and love." },
  { id: 26, title: "Bonus: “Redeem When You Want Me”", body: "No expiration. No limit. No questions asked. Just come find me." }
];